# This is a basic workflow to help you get started with Actions

name: Approve PR

on:
  workflow_dispatch:
    inputs:
      pr_number:
        description: "PR number"
        required: true
        type: number

permissions:
  pull-requests: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Approve PR
        run: |
          echo "Approving PR ${{ github.event.inputs.pr_number }}"
          gh pr review ${{ github.event.inputs.pr_number }} --approve
        env:
          GH_TOKEN: ${{ github.token }}
