# This is a basic workflow to help you get started with Actions

name: Approve PR

on:
  workflow_dispatch:
    inputs:
      pr_number:
        description: "PR number"
        required: true
        type: number

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      # Runs a single command using the runners shell
      - name: Approve PR
        run: |
          echo "Approving PR ${{ github.event.inputs.pr_number }}"
          gh pr review ${{ github.event.inputs.pr_number }} --approve
